const {Client,GatewayIntentBits,SlashCommandBuilder,REST,Routes,EmbedBuilder}=require("discord.js");
const {joinVoiceChannel,createAudioPlayer,createAudioResource,AudioPlayerStatus}=require("@discordjs/voice");
const playdl=require("play-dl");
const TOKEN=process.env.TOKEN;
const CLIENT_ID=process.env.CLIENT_ID||"1500092889701810256";
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates,GatewayIntentBits.GuildMessages]});
const queues=new Map();
const rest=new REST({version:"10"}).setToken(TOKEN);
const commands=[new SlashCommandBuilder().setName("play").setDescription("Play musik dari SoundCloud").addStringOption(o=>o.setName("judul").setDescription("Judul lagu").setRequired(true)),new SlashCommandBuilder().setName("skip").setDescription("Skip"),new SlashCommandBuilder().setName("stop").setDescription("Stop"),new SlashCommandBuilder().setName("queue").setDescription("Antrian"),new SlashCommandBuilder().setName("pause").setDescription("Pause"),new SlashCommandBuilder().setName("resume").setDescription("Resume")].map(c=>c.toJSON());
rest.put(Routes.applicationCommands(CLIENT_ID),{body:commands}).then(()=>console.log("Commands terdaftar!")).catch(console.error);
function playNext(guildId){const q=queues.get(guildId);if(!q||q.songs.length===0){q?.connection?.destroy();queues.delete(guildId);return;}const song=q.songs[0];const embed=new EmbedBuilder().setColor(0x9B59B6).setTitle("⏳ Loading...").setDescription(song.title).setFooter({text:"Vernon X DFS Music BOT"});q.textChannel.send({embeds:[embed]});playdl.stream(song.url,{discordPlayerCompatibility:true}).then(stream=>{const resource=createAudioResource(stream.stream,{inputType:stream.type});q.player.play(resource);const nowEmbed=new EmbedBuilder().setColor(0x2ECC71).setTitle("▶️ Sekarang Memutar").setDescription(song.title).addFields({name:"Request by",value:song.requestBy||"Unknown",inline:true}).setFooter({text:"Vernon X DFS Music BOT"});q.textChannel.send({embeds:[nowEmbed]});q.player.once(AudioPlayerStatus.Idle,()=>{q.songs.shift();playNext(guildId);});}).catch(e=>{q.textChannel.send("❌ Gagal: "+e.message);q.songs.shift();playNext(guildId);});}
client.once("ready",()=>console.log("Bot online: "+client.user.tag));
client.on("interactionCreate",async interaction=>{if(!interaction.isChatInputCommand())return;const{commandName,guild,member}=interaction;if(commandName==="play"){const vc=member.voice.channel;if(!vc)return interaction.reply({content:"❌ Masuk voice channel dulu!",ephemeral:true});const judul=interaction.options.getString("judul");await interaction.deferReply();try{const results=await playdl.search(judul,{source:{soundcloud:"tracks"},limit:1});if(!results||results.length===0)return await interaction.editReply("❌ Lagu tidak ditemukan!");const track=results[0];const song={title:track.name,url:track.url,requestBy:member.user.username};let q=queues.get(guild.id);if(!q){const player=createAudioPlayer();const connection=joinVoiceChannel({channelId:vc.id,guildId:guild.id,adapterCreator:guild.voiceAdapterCreator});connection.subscribe(player);q={connection,player,songs:[song],textChannel:interaction.channel};queues.set(guild.id,q);const embed=new EmbedBuilder().setColor(0x3498DB).setTitle("🎵 Ditambahkan ke Antrian").setDescription(track.name).addFields({name:"Request by",value:member.user.username,inline:true}).setFooter({text:"Vernon X DFS Music BOT"});await interaction.editReply({embeds:[embed]});playNext(guild.id);}else{q.songs.push(song);const embed=new EmbedBuilder().setColor(0x3498DB).setTitle("✅ Ditambahkan ke Antrian").setDescription(track.name).setFooter({text:"Vernon X DFS Music BOT"});await interaction.editReply({embeds:[embed]});}}catch(e){await interaction.editReply("❌ Gagal: "+e.message);}}else if(commandName==="skip"){const q=queues.get(guild.id);if(!q)return interaction.reply("❌ Tidak ada musik!");q.player.stop();interaction.reply("⏭️ Di-skip!");}else if(commandName==="stop"){const q=queues.get(guild.id);if(!q)return interaction.reply("❌ Tidak ada musik!");q.songs=[];q.player.stop();q.connection.destroy();queues.delete(guild.id);interaction.reply("⏹️ Musik dihentikan.");}else if(commandName==="queue"){const q=queues.get(guild.id);if(!q||q.songs.length===0)return interaction.reply("📭 Antrian kosong!");const embed=new EmbedBuilder().setColor(0x9B59B6).setTitle("🎶 Antrian Lagu").setDescription(q.songs.map((s,i)=>(i===0?"▶️ ":"　"+(i+1)+". ")+s.title).join("\n")).setFooter({text:"Vernon X DFS Music BOT"});interaction.reply({embeds:[embed]});}else if(commandName==="pause"){const q=queues.get(guild.id);if(!q)return interaction.reply("❌ Tidak ada musik!");q.player.pause();interaction.reply("⏸️ Di-pause.");}else if(commandName==="resume"){const q=queues.get(guild.id);if(!q)return interaction.reply("❌ Tidak ada musik!");q.player.unpause();interaction.reply("▶️ Dilanjutkan.");}});
client.login(TOKEN);
