const TOKEN=process.env.TOKEN;const TOKEN=process.env.TOKEN;const {Client,GatewayIntentBits,SlashCommandBuilder,REST,Routes,EmbedBuilder}=require("discord.js");
const {joinVoiceChannel,createAudioPlayer,createAudioResource,AudioPlayerStatus}=require("@discordjs/voice");
const {execSync,exec}=require("child_process");
const fs=require("fs");
const path=require("path");
const TOKEN="MTUwMDA5Mjg4OTcwMTgxMDI1Ng.G0cRbZ.X3lkSynVDQRw3ptHwuogpKA5BF1YzfDRpxCXF0";
const CLIENT_ID="1500092889701810256";
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates,GatewayIntentBits.GuildMessages]});
const queues=new Map();
const rest=new REST({version:"10"}).setToken(TOKEN);
const commands=[new SlashCommandBuilder().setName("play").setDescription("Play musik").addStringOption(o=>o.setName("url").setDescription("URL YouTube").setRequired(true)),new SlashCommandBuilder().setName("skip").setDescription("Skip"),new SlashCommandBuilder().setName("stop").setDescription("Stop"),new SlashCommandBuilder().setName("queue").setDescription("Antrian"),new SlashCommandBuilder().setName("pause").setDescription("Pause"),new SlashCommandBuilder().setName("resume").setDescription("Resume")].map(c=>c.toJSON());
rest.put(Routes.applicationCommands(CLIENT_ID),{body:commands}).then(()=>console.log("Commands terdaftar!")).catch(console.error);
function getInfo(url){try{const out=execSync('yt-dlp --dump-json --no-playlist "'+url+'" 2>/dev/null').toString().trim();return JSON.parse(out);}catch(e){return null;}}
function playNext(guildId){const q=queues.get(guildId);if(!q||q.songs.length===0){q?.connection?.destroy();queues.delete(guildId);return;}const song=q.songs[0];const file=path.join(__dirname,"music_"+guildId+".mp3");const embed=new EmbedBuilder().setColor(0x9B59B6).setTitle("⏳ Loading...").setDescription("["+song.title+"]("+song.url+")").setThumbnail(song.thumb).setFooter({text:"Vernon X DFS Music BOT"});q.textChannel.send({embeds:[embed]});exec('yt-dlp -x --audio-format mp3 --audio-quality 0 -o "'+file+'" "'+song.url+'" 2>/dev/null',(err)=>{if(err){q.textChannel.send("❌ Gagal download lagu!");q.songs.shift();playNext(guildId);return;}const resource=createAudioResource(file);q.player.play(resource);const nowEmbed=new EmbedBuilder().setColor(0x2ECC71).setTitle("▶️ Sekarang Memutar").setDescription("["+song.title+"]("+song.url+")").setThumbnail(song.thumb).addFields({name:"Durasi",value:song.duration||"N/A",inline:true},{name:"Request by",value:song.requestBy||"Unknown",inline:true}).setFooter({text:"Vernon X DFS Music BOT"});q.textChannel.send({embeds:[nowEmbed]});q.player.once(AudioPlayerStatus.Idle,()=>{try{fs.unlinkSync(file);}catch(e){}q.songs.shift();playNext(guildId);});});}
client.once("clientReady",()=>console.log("Bot online: "+client.user.tag));
client.on("interactionCreate",async interaction=>{if(!interaction.isChatInputCommand())return;const{commandName,guild,member}=interaction;if(commandName==="play"){const vc=member.voice.channel;if(!vc)return interaction.reply({content:"❌ Masuk voice channel dulu!",ephemeral:true});const url=interaction.options.getString("url");await interaction.deferReply();try{const info=getInfo(url);const title=info?info.title:"Lagu";const thumb=info?info.thumbnail:"";const duration=info?new Date(info.duration*1000).toISOString().substr(11,8):"N/A";const song={title,url,thumb,duration,requestBy:member.user.username};let q=queues.get(guild.id);if(!q){const player=createAudioPlayer();const connection=joinVoiceChannel({channelId:vc.id,guildId:guild.id,adapterCreator:guild.voiceAdapterCreator});connection.subscribe(player);q={connection,player,songs:[song],textChannel:interaction.channel};queues.set(guild.id,q);const embed=new EmbedBuilder().setColor(0x3498DB).setTitle("🎵 Ditambahkan ke Antrian").setDescription("["+title+"]("+url+")").setThumbnail(thumb).addFields({name:"Durasi",value:duration,inline:true},{name:"Request by",value:member.user.username,inline:true}).setFooter({text:"Vernon X DFS Music BOT"});await interaction.editReply({embeds:[embed]});playNext(guild.id);}else{q.songs.push(song);const embed=new EmbedBuilder().setColor(0x3498DB).setTitle("✅ Ditambahkan ke Antrian").setDescription("["+title+"]("+url+")").setThumbnail(thumb).addFields({name:"Posisi",value:"#"+q.songs.length,inline:true},{name:"Request by",value:member.user.username,inline:true}).setFooter({text:"Vernon X DFS Music BOT"});await interaction.editReply({embeds:[embed]});}}catch(e){await interaction.editReply("❌ Gagal: "+e.message);}}else if(commandName==="skip"){const q=queues.get(guild.id);if(!q)return interaction.reply("❌ Tidak ada musik!");q.player.stop();interaction.reply("⏭️ Di-skip!");}else if(commandName==="stop"){const q=queues.get(guild.id);if(!q)return interaction.reply("❌ Tidak ada musik!");q.songs=[];q.player.stop();q.connection.destroy();queues.delete(guild.id);interaction.reply("⏹️ Musik dihentikan.");}else if(commandName==="queue"){const q=queues.get(guild.id);if(!q||q.songs.length===0)return interaction.reply("📭 Antrian kosong!");const embed=new EmbedBuilder().setColor(0x9B59B6).setTitle("🎶 Antrian Lagu").setDescription(q.songs.map((s,i)=>(i===0?"▶️ ":"　"+(i+1)+". ")+s.title).join("\n")).setFooter({text:"Vernon X DFS Music BOT"});interaction.reply({embeds:[embed]});}else if(commandName==="pause"){const q=queues.get(guild.id);if(!q)return interaction.reply("❌ Tidak ada musik!");q.player.pause();interaction.reply("⏸️ Di-pause.");}else if(commandName==="resume"){const q=queues.get(guild.id);if(!q)return interaction.reply("❌ Tidak ada musik!");q.player.unpause();interaction.reply("▶️ Dilanjutkan.");}});
client.login(TOKEN);
